version: '3.4'

services:
    sqldata:
        environment:
          - SA_PASSWORD=Pass@word
          - ACCEPT_EULA=Y
        ports:
          - "5433:1433"
        volumes:
          - eshop-sqldata:/var/opt/mssql

    catalog-api:
        env_file:
                - catalog.env

        ports:
            - "5101:80"
            - "9101:81"

volumes:
    eshop-sqldata:
        external: false

